join-titles:
  -
    title: "&7&lWelcome to &a&lMinecord Network"
    sub-title: "&f&lWe hope you'll enjoy the game!"
    stay: 5
  -
    title: "&e&lThis is a title"
    sub-title: "&a&lAnd this is subtitle (surprise!)"
    stay: 3

chat-messages:
  prefix: "&e[Tip]"
  delay: 60

  # You can add your own groups, permission will be messagenotifier.group.<groupName>
  # Player will be always receiving messages from group default and all groups if he has permissions for it
  groups:
    # No permission required
    default:
      - "{prefix} &7This is just a test &aDEFAULT &7message"

    # Permission required: messagenotifier.group.hero
    hero:
      - "{prefix} &7This is just a test &bHERO &7message"